# Generated by Django 3.1.7 on 2021-07-18 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_phase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerbookname', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/ads_pic')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assign_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.jobs')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assign_deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.deals')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
