# Generated by Django 3.1.7 on 2021-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refferalcode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
