# Generated by Django 3.1.7 on 2021-08-21 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_phase', '0002_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_notifications',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile'),
        ),
        migrations.AlterField(
            model_name='personal_notifications',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
