# Generated by Django 3.1.7 on 2021-08-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0003_auto_20210822_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbook',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_phase.products'),
            preserve_default=False,
        ),
    ]
