# Generated by Django 3.1.7 on 2021-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0003_auto_20210814_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='publish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
