# Generated by Django 3.1.7 on 2021-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0003_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refferalcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
