# Generated by Django 3.1.7 on 2021-08-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0004_products_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='apresentacao',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='products',
            name='published_date',
        ),
    ]
