# Generated by Django 3.1.7 on 2021-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0007_auto_20210325_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pic'),
        ),
    ]
