# Generated by Django 3.1.7 on 2021-04-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0009_deals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='attachments',
            field=models.ImageField(blank=True, null=True, upload_to='deals/deals_attachments'),
        ),
        migrations.AlterField(
            model_name='deals',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='deals/deals_pic'),
        ),
    ]
