# Generated by Django 3.1.7 on 2021-04-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0010_auto_20210404_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='deals/deals_attachments'),
        ),
    ]
