# Generated by Django 3.1.7 on 2021-04-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0011_auto_20210404_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='attachments',
        ),
        migrations.CreateModel(
            name='attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='deals/deals_attachments')),
                ('deals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.deals')),
            ],
        ),
    ]
