# Generated by Django 3.1.7 on 2021-04-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0013_remove_attachments_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='deals/deals_attachments'),
        ),
    ]
