# Generated by Django 3.1.7 on 2021-04-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0015_auto_20210405_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='deal',
        ),
    ]
