# Generated by Django 3.1.7 on 2021-04-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0017_attachments_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
