# Generated by Django 3.1.7 on 2021-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0018_auto_20210405_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deals',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
