# Generated by Django 3.1.7 on 2021-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0020_auto_20210410_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_attachments',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='jobs/jobs_attachments'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/jobs_pic'),
        ),
    ]
