# Generated by Django 3.1.7 on 2021-04-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0023_product_attachments_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_attachments',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.products'),
        ),
    ]
