# Generated by Django 3.1.7 on 2021-04-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0025_auto_20210410_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refferalcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
