# Generated by Django 3.1.7 on 2021-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0028_assign_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_deal',
            name='assigns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
