# Generated by Django 3.1.7 on 2021-05-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0033_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile'),
        ),
    ]
