# Generated by Django 3.1.7 on 2021-05-04 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0035_auto_20210505_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deal_cart',
        ),
    ]
