# Generated by Django 3.1.7 on 2021-05-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0038_auto_20210505_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_wish',
            old_name='deal',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='product_cart',
            old_name='deal',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product_wish',
            old_name='deal',
            new_name='product',
        ),
    ]
