# Generated by Django 3.1.7 on 2021-05-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0039_auto_20210505_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_wish',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.jobs'),
        ),
        migrations.AlterField(
            model_name='product_cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.products'),
        ),
        migrations.AlterField(
            model_name='product_wish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.products'),
        ),
    ]
