# Generated by Django 3.1.7 on 2021-05-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0040_auto_20210505_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
