# Generated by Django 3.1.7 on 2021-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0041_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
    ]
