# Generated by Django 3.1.7 on 2021-05-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0044_auto_20210509_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.BigIntegerField(blank=True, default='0', null=True),
        ),
    ]
