# Generated by Django 3.1.7 on 2021-05-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0045_auto_20210509_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_deal',
            name='assigns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
