# Generated by Django 3.1.7 on 2021-05-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0046_assign_deal_assigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
