# Generated by Django 3.1.7 on 2021-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0047_auto_20210512_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='quantity',
            field=models.BigIntegerField(blank=True, default='1', null=True),
        ),
    ]
