# Generated by Django 3.1.7 on 2021-05-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0051_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.address')),
            ],
        ),
    ]
