# Generated by Django 3.1.7 on 2021-05-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0053_auto_20210521_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
