# Generated by Django 3.1.7 on 2021-05-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0055_orders_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
