# Generated by Django 3.1.7 on 2021-05-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0057_auto_20210521_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='ordered', max_length=100, null=True),
        ),
    ]
