# Generated by Django 3.1.7 on 2021-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0058_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
