# Generated by Django 3.1.7 on 2021-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0059_orders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.IntegerField(blank=True, default='10', null=True),
        ),
    ]
