# Generated by Django 3.1.7 on 2021-05-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0060_orders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myrefferalid',
            field=models.CharField(blank=True, default='EBWD', max_length=100),
        ),
    ]
