# Generated by Django 3.1.7 on 2021-05-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0061_profile_myrefferalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='myrefferalid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
