# Generated by Django 3.1.7 on 2021-06-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0063_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myrefferalcount',
            field=models.BigIntegerField(blank=True, default='0', null=True),
        ),
    ]
