# Generated by Django 3.1.7 on 2021-06-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0064_profile_myrefferalcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, default='0000000000', null=True),
        ),
    ]
