# Generated by Django 3.1.7 on 2021-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0065_auto_20210604_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
