# Generated by Django 3.1.7 on 2021-06-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0066_auto_20210605_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_name']},
        ),
    ]
