# Generated by Django 3.1.7 on 2021-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0067_auto_20210605_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['location']},
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BigIntegerField(blank=True, default='0', null=True),
        ),
    ]
