# Generated by Django 3.1.7 on 2021-06-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0068_auto_20210605_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='oldprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
