# Generated by Django 3.1.7 on 2021-06-06 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_phase', '0069_products_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='orders/orders_pic'),
        ),
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(blank=True, max_length=100)),
                ('clicksall', models.BigIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile-pic')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='adclicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userclicks', models.BigIntegerField(blank=True, default=0, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_phase.ads')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
