# Generated by Django 3.1.7 on 2021-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0070_auto_20210606_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/ads_pic'),
        ),
    ]
