# Generated by Django 3.1.7 on 2021-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0072_auto_20210607_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adclicks',
            name='userclicks',
            field=models.BigIntegerField(blank=True, default='0', null=True),
        ),
    ]
