# Generated by Django 3.1.7 on 2021-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0073_auto_20210607_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='adsize',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
