# Generated by Django 3.1.7 on 2021-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0077_auto_20210608_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adclicks',
            name='userclicks',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
