# Generated by Django 3.1.7 on 2021-06-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0079_adclicks_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adclicks',
            old_name='user',
            new_name='useris',
        ),
    ]
