# Generated by Django 3.1.7 on 2021-06-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0080_auto_20210608_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adclicks',
            name='useris',
        ),
        migrations.AddField(
            model_name='adclicks',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile'),
            preserve_default=False,
        ),
    ]
