# Generated by Django 3.1.7 on 2021-06-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0082_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategorycount',
            field=models.BigIntegerField(blank=True, default='0', null=True),
        ),
    ]
