# Generated by Django 3.1.7 on 2021-06-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0085_auto_20210609_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='category',
        ),
        migrations.AddField(
            model_name='deals',
            name='category',
            field=models.ManyToManyField(to='admin_phase.categorys'),
        ),
    ]
