# Generated by Django 3.1.7 on 2021-06-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0086_auto_20210609_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
        migrations.AddField(
            model_name='jobs',
            name='category',
            field=models.ManyToManyField(to='admin_phase.categorys'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='admin_phase.categorys'),
        ),
    ]
