# Generated by Django 3.1.7 on 2021-06-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0087_auto_20210609_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='slug',
            field=models.SlugField(blank=True, max_length=900, null=True),
        ),
    ]
