# Generated by Django 3.1.7 on 2021-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0088_auto_20210612_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
