# Generated by Django 3.1.7 on 2021-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0089_auto_20210612_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
