# Generated by Django 3.1.7 on 2021-06-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_phase', '0091_auto_20210620_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_deal',
            name='assigns',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_phase.profile'),
            preserve_default=False,
        ),
    ]
